// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJeY5ffIA4Zhh2LY9-84tmqQ5Fq_VdOko',
    appId: '1:979051290141:web:ee4ceb8f7f3eb2dbd270f4',
    messagingSenderId: '979051290141',
    projectId: 'chat-59ff5',
    authDomain: 'chat-59ff5.firebaseapp.com',
    storageBucket: 'chat-59ff5.appspot.com',
    measurementId: 'G-8GSGHBVQXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8QAI45UOP_blTVigm5T3CyUyya6sdxh8',
    appId: '1:979051290141:android:03d1b504ceac801cd270f4',
    messagingSenderId: '979051290141',
    projectId: 'chat-59ff5',
    storageBucket: 'chat-59ff5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgVf0q_UiUtnjEXi8e7FSlZ8iJNMOjnk',
    appId: '1:979051290141:ios:b06d6a6f24ca0defd270f4',
    messagingSenderId: '979051290141',
    projectId: 'chat-59ff5',
    storageBucket: 'chat-59ff5.appspot.com',
    iosBundleId: 'com.example.chat01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgVf0q_UiUtnjEXi8e7FSlZ8iJNMOjnk',
    appId: '1:979051290141:ios:b06d6a6f24ca0defd270f4',
    messagingSenderId: '979051290141',
    projectId: 'chat-59ff5',
    storageBucket: 'chat-59ff5.appspot.com',
    iosBundleId: 'com.example.chat01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJeY5ffIA4Zhh2LY9-84tmqQ5Fq_VdOko',
    appId: '1:979051290141:web:452d755f5b8de5e9d270f4',
    messagingSenderId: '979051290141',
    projectId: 'chat-59ff5',
    authDomain: 'chat-59ff5.firebaseapp.com',
    storageBucket: 'chat-59ff5.appspot.com',
    measurementId: 'G-Q2W5KM4K9R',
  );
}
